const popularContent = [
    {
        id: "1",
        type: "굿즈",
        username: "김붕어",
        date: "2024.12.03",
        image: require("../../../assets/images/product1.png"),
        title: "황금 붕어빵 (삼호점)",
        review: "정말 맛있어요!",
        rating: 4.5,
    },
    {
        id: "2",
        type: "매장",
        username: "박잉어",
        date: "2024.12.04",
        image: require("../../../assets/images/product2.png"),
        title: "찰떡 붕어빵 (서울점)",
        review: "바삭하고 달콤합니다.",
        rating: 3.5,
    },
    {
        id: "3",
        type: "굿즈",
        username: "최붕붕",
        date: "2024.12.05",
        image: require("../../../assets/images/product4.png"),
        title: "슈퍼 붕어빵 (부산점)",
        review: "다시 방문하고 싶어요!",
        rating: 3.9,
    },
    {
        id: "3",
        type: "매장",
        username: "최붕붕",
        date: "2024.12.05",
        image: require("../../../assets/images/product6.png"),
        title: "슈퍼 붕어빵 (부산점)",
        review: "다시 방문하고 싶어요!",
        rating: 3.0,
    },
    {
        id: "4",
        type: "굿즈",
        username: "최붕붕",
        date: "2024.12.05",
        image: require("../../../assets/images/product3.png"),
        title: "슈퍼 붕어빵 (부산점)",
        review: "다시 방문하고 싶어요!",
        rating: 3.0,
    },
    {
        id: "5",
        type: "매장",
        username: "최붕붕",
        date: "2024.12.05",
        image: require("../../../assets/images/product2.png"),
        title: "슈퍼 붕어빵 (부산점)",
        review: "다시 방문하고 싶어요!",
        rating: 1.0,
    },
    {
        id: "6",
        type: "굿즈",
        username: "최붕붕",
        date: "2024.12.05",
        image: require("../../../assets/images/product1.png"),
        title: "슈퍼 붕어빵 (부산점)",
        review: "다시 방문하고 싶어요!",
        rating: 2.0,
    },
    {
        id: "7",
        type: "매장",
        username: "최붕붕",
        date: "2024.12.05",
        image: require("../../../assets/images/product3.png"),
        title: "슈퍼 붕어빵 (부산점)",
        review: "다시 방문하고 싶어요!",
        rating: 3.0,
    },
    {
        id: "8",
        type: "굿즈",
        username: "최붕붕",
        date: "2024.12.05",
        image: require("../../../assets/images/product1.png"),
        title: "슈퍼 붕어빵 (부산점)",
        review: "다시 방문하고 싶어요!",
        rating: 4.0,
    },
    {
        id: "9",
        type: "매장",
        username: "최붕붕",
        date: "2024.12.05",
        image: require("../../../assets/images/product5.png"),
        title: "슈퍼 붕어빵 (부산점)",
        review: "다시 방문하고 싶어요!",
        rating: 4.0,
    },
    {
        id: "10",
        type: "굿즈",
        username: "최붕붕",
        date: "2024.12.05",
        image: require("../../../assets/images/product2.png"),
        title: "슈퍼 붕어빵 (부산점)",
        review: "다시 방문하고 싶어요!",
        rating: 3.0,
    },
    {
        id: "11",
        type: "매장",
        username: "최붕붕",
        date: "2024.12.05",
        image: require("../../../assets/images/product6.png"),
        title: "슈퍼 붕어빵 (부산점)",
        review: "다시 방문하고 싶어요!",
        rating: 4.3,
    },
    {
        id: "12",
        type: "굿즈",
        username: "최붕붕",
        date: "2024.12.05",
        image: require("../../../assets/images/product3.png"),
        title: "슈퍼 붕어빵 (부산점)",
        review: "다시 방문하고 싶어요!",
        rating: 4.0,
    },
    {
        id: "13",
        type: "매장",
        username: "최붕붕",
        date: "2024.12.05",
        image: require("../../../assets/images/product5.png"),
        title: "슈퍼 붕어빵 (부산점)",
        review: "다시 방문하고 싶어요!",
        rating: 3.5,
    },
    {
        id: "14",
        type: "굿즈",
        username: "최붕붕",
        date: "2024.12.05",
        image: require("../../../assets/images/product5.png"),
        title: "슈퍼 붕어빵 (부산점)",
        review: "다시 방문하고 싶어요!",
        rating: 2.0,
    },
    {
        id: "15",
        type: "매장",
        username: "최붕붕",
        date: "2024.12.05",
        image: require("../../../assets/images/product4.png"),
        title: "슈퍼 붕어빵 (부산점)",
        review: "다시 방문하고 싶어요!",
        rating: 1.0,
    },
];

export default popularContent;