const PRODUCTS = [
	{ id: '1', category: '악세서리', name: '붕어빵 키링', price: '1,500원', image: require('../../../assets/images/product1.png') },
	{ id: '2', category: '악세서리', name: '붕어빵 폰케이스', price: '3,000원', image: require('../../../assets/images/product2.png') },
	{ id: '3', category: '인형', name: '붕어빵 인형', price: '5,000원', image: require('../../../assets/images/product3.png') },
	{ id: '4', category: '생활용품', name: '붕어빵 메이커', price: '10,000원', image: require('../../../assets/images/product4.png') },
	{ id: '5', category: '악세서리', name: '붕어빵 키링', price: '20,000원', image: require('../../../assets/images/product5.png') },
	{ id: '6', category: '악세서리', name: '붕어빵 폰케이스', price: '13,000원', image: require('../../../assets/images/product6.png') },
	{ id: '7', category: '인형', name: '붕어빵 전신인형', price: '23,000원', image: require('../../../assets/images/product1.png') },
	{ id: '8', category: '인형', name: '붕어빵 전신인형', price: '25,000원', image: require('../../../assets/images/product2.png') },
	{ id: '9', category: '악세서리', name: '붕어빵 귀걸이', price: '7,000원', image: require('../../../assets/images/product3.png') },
	{ id: '10', category: '인형', name: '붕어빵 미니인형', price: '10,000원', image: require('../../../assets/images/product4.png') },
	{ id: '11', category: '인형', name: '붕어빵 미니인형', price: '10,000원', image: require('../../../assets/images/product5.png') },
	{ id: '12', category: '생활용품', name: '붕어빵 오븐', price: '30,000원', image: require('../../../assets/images/product6.png') },
	{ id: '13', category: '생활용품', name: '붕어빵 쉐이커', price: '35,000원', image: require('../../../assets/images/product3.png') },
	{ id: '14', category: '생활용품', name: '붕어빵 타월', price: '21,000원', image: require('../../../assets/images/product5.png') },
	{ id: '15', category: '생활용품', name: '붕어빵 그릇', price: '10,000원', image: require('../../../assets/images/product6.png') },
	{ id: '16', category: '악세서리', name: '붕어빵 그립톡', price: '3,500원', image: require('../../../assets/images/product5.png') },
	{ id: '17', category: '악세서리', name: '붕어빵 그립톡', price: '4,000원', image: require('../../../assets/images/product3.png') },
	{ id: '18', category: '인형', name: '붕어빵 미니인형', price: '7,000원', image: require('../../../assets/images/product3.png') },
	{ id: '19', category: '생활용품', name: '붕어빵 메이커', price: '11,000원', image: require('../../../assets/images/product4.png') },
	{ id: '20', category: '악세서리', name: '붕어빵 폰케이스', price: '23,000원', image: require('../../../assets/images/product5.png') },
	{ id: '21', category: '악세서리', name: '붕어빵 폰케이스', price: '43,000원', image: require('../../../assets/images/product6.png') },
	{ id: '22', category: '인형', name: '붕어빵 전신인형', price: '123,000원', image: require('../../../assets/images/product1.png') },
	{ id: '23', category: '인형', name: '붕어빵 붕순이', price: '205,000원', image: require('../../../assets/images/product2.png') },
	{ id: '24', category: '악세서리', name: '붕어빵 귀걸이', price: '17,000원', image: require('../../../assets/images/product3.png') },
	{ id: '25', category: '인형', name: '붕어빵 붕순이', price: '130,000원', image: require('../../../assets/images/product4.png') },
	{ id: '26', category: '인형', name: '붕어빵 붕순이', price: '5,000원', image: require('../../../assets/images/product5.png') },
	{ id: '27', category: '생활용품', name: '붕어빵 오븐', price: '3,000원', image: require('../../../assets/images/product5.png') },
	{ id: '28', category: '생활용품', name: '붕어빵 쉐이커', price: '305,000원', image: require('../../../assets/images/product4.png') },
	{ id: '29', category: '생활용품', name: '붕어빵 타월', price: '231,000원', image: require('../../../assets/images/product3.png') },
	{ id: '30', category: '생활용품', name: '붕어빵 그릇', price: '101,000원', image: require('../../../assets/images/product1.png') },
  ];

  export default PRODUCTS;